baseurl: /willmeesearch.com
languageCode: en-us
title: "William B. Meese"
theme: "anatole"
googleAnalytics: ''
disqusShortname: ''
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  post: /:year/:month/:day/:slug/
menu:
  main:
    - name: About
      url: /about/
    - name: Research
      url: /research/
    - name: CV
      url: /vitae/
    - name: GitHub
      url: https://github.com/meesew
    - name: Twitter
      url: https://twitter.com/meesewilliam
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: "Social | Health Psychologist (**in prep**)""
  favicon: favicon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  profilePicture: images/profile.jpg
  logo:
    alt: Logo
    height: 50
    url: logo.png
    width: 50
